site_name: Parthiban Rajendran
docs_dir: mkdocs/docs/
plugins:
    - search
theme: 
  name: readthedocs
  custom_dir: mkdocs/custom_theme/
extra_css:
  - css/extra.css
  # - css/nbheader_styles_MOD.css
  - css/pdfextra.css


